/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "s21_decimal.h"

/////////////////////////
// CONVERSION
/////////////////////////

// S21_INT_TO_DECIMAl
//---------------------------------------
START_TEST(int_to_decimal_1) {
  s21_decimal x = {{0}};
  int y = 3;
  s21_decimal result = {{3, 0, 0, 0}};
  int return_code = s21_from_int_to_decimal(y, &x);
  int return_value = s21_is_equal(result, x);
  ck_assert_int_eq(return_value, 1);
  ck_assert_int_eq(return_code, 0);
}
END_TEST

START_TEST(int_to_decimal_2) {
  s21_decimal x = {{0}};
  int y = 50;
  s21_decimal result = {{3, 0, 0, 0}};
  int return_code = s21_from_int_to_decimal(y, &x);
  int return_value = s21_is_equal(result, x);
  ck_assert_int_eq(return_value, 0);
  ck_assert_int_eq(return_code, 0);
}
END_TEST

START_TEST(int_to_decimal_3) {
  s21_decimal x = {{0}};
  int y = INT32_MAX;
  s21_decimal result = {{2147483647, 0, 0, 0}};
  int return_code = s21_from_int_to_decimal(y, &x);
  int return_value = s21_is_equal(result, x);
  ck_assert_int_eq(return_value, 1);
  ck_assert_int_eq(return_code, 0);
}
END_TEST

START_TEST(int_to_decimal_4) {
  s21_decimal x = {{0}};
  int y = -INT32_MAX;
  s21_decimal result = {{2147483647, 0, 0, NEGATIVE_INT}};
  int return_code = s21_from_int_to_decimal(y, &x);
  int return_value = s21_is_equal(result, x);
  ck_assert_int_eq(return_value, 1);
  ck_assert_int_eq(return_code, 0);
}
END_TEST

START_TEST(int_to_decimal_5) {
  s21_decimal x = {{0}};
  int y = -5;
  s21_decimal result = {{5, 0, 0, NEGATIVE_INT}};
  int return_code = s21_from_int_to_decimal(y, &x);
  int return_value = s21_is_equal(result, x);
  ck_assert_int_eq(return_value, 1);
  ck_assert_int_eq(return_code, 0);
}
END_TEST

START_TEST(int_to_decimal_6) {
  s21_decimal x = {{0}};
  int y = 0;
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_from_int_to_decimal(y, &x);
  int return_value = s21_is_equal(result, x);
  ck_assert_int_eq(return_value, 1);
  ck_assert_int_eq(return_code, 0);
}
END_TEST

START_TEST(int_to_decimal_7) {
  s21_decimal x = {{0}};
  int y = -0;
  s21_decimal result = {{0, 0, 0, NEGATIVE_INT}};
  int return_code = s21_from_int_to_decimal(y, &x);
  int return_value = s21_is_equal(result, x);
  ck_assert_int_eq(return_value, 1);
  ck_assert_int_eq(return_code, 0);

  // S21_DECIMAL_TO_INT
  //---------------------------------------
}
END_TEST

START_TEST(decimal_to_int_1) {
  s21_decimal x = {{0, 0, 0, 0}};
  int y = 0;
  int result = 0;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(result, y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_2) {
  s21_decimal x = {{INT32_MAX, 0, 0, 0}};
  int y = 0;
  int result = INT32_MAX;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(result, y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_3) {
  s21_decimal x = {{INT32_MAX, 0, 0, NEGATIVE_INT}};
  int y = 0;
  int result = -INT32_MAX;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(result, y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_4) {
  s21_decimal x = {{INT32_MIN + 1, 0, 0, NEGATIVE_INT}};
  int y = 0;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 1);  // error
}
END_TEST

START_TEST(decimal_to_int_5) {
  s21_decimal x = {{1234, 0, 0, 0}};
  set_scale(2, &x);
  int y = 0;
  int result = 12;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(result, y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_6) {
  s21_decimal x = {{1234, 0, 0, NEGATIVE_INT}};
  set_scale(2, &x);
  int y = 0;
  int result = -12;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(result, y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_7) {
  s21_decimal x = {{1234, 0, 0, 0}};
  int y = 0;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 0);  // error
}
END_TEST

START_TEST(decimal_to_int_8) {
  s21_decimal x = {{INT32_MIN, 0, 0, NEGATIVE_INT}};
  int y = 0;
  int result = -2147483648;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_9) {
  s21_decimal x = {{INT32_MAX - 1, 0, 0, NEGATIVE_INT}};
  int y = 0;
  int result = -2147483646;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_10) {
  s21_decimal x = {{2151694848, 0, 0, 0}};
  int y = 0;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 1);  // error
}
END_TEST

START_TEST(decimal_to_int_11) {
  s21_decimal x = {{266240, 268689408, 0, 0}};
  int y = 0;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 1);  // error
}
END_TEST

START_TEST(decimal_to_int_12) {
  // 4835703.280780685256823548
  s21_decimal x = {{135932, 540672, 262144, NEGATIVE_INT}};
  set_scale(18, &x);
  int y = 0;
  int result = -4835703;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_13) {
  // -483570327.8528885443526656
  s21_decimal x = {{524288, 16384, 262144, NEGATIVE_INT}};
  set_scale(16, &x);
  int y = 0;
  int result = -483570327;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(y, result);
}
END_TEST

START_TEST(decimal_to_int_14) {
  // 2147483648.398
  s21_decimal x = {{398, 500, 0, 0}};
  set_scale(3, &x);
  int y = 0;
  int return_code = s21_from_decimal_to_int(x, &y);
  ck_assert_int_eq(return_code, 1);  // error

  // S21_FLOAT_TO_DECIMAL
  //---------------------------------------
}
END_TEST

START_TEST(float_to_decimal_1) {
  s21_decimal dst = {{0}};
  float src = 1234.56;
  s21_decimal result = {{123456, 0, 0, 131072}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_2) {
  s21_decimal dst = {{0}};
  float src = 5.56;
  s21_decimal result = {{556, 0, 0, 131072}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_3) {
  s21_decimal dst = {{0}};
  float src = 5.647812;
  s21_decimal result = {{5647812, 0, 0, 393216}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_4) {
  s21_decimal dst = {{0}};
  float src = 0.05;
  s21_decimal result = {{5, 0, 0, 131072}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_5) {
  s21_decimal dst = {{0}};
  float src = 0.005;
  s21_decimal result = {{5, 0, 0, 196608}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_6) {
  s21_decimal dst = {{0}};
  float src = -0.5;
  s21_decimal result = {{5, 0, 0, 2147549184}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_7) {
  s21_decimal dst = {{0}};
  float src = -0.05;
  s21_decimal result = {{5, 0, 0, 2147614720}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_8) {
  s21_decimal dst = {{0}};
  float src = 0.2147483;
  s21_decimal result = {{214748, 0, 0, 393216}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_9) {
  s21_decimal dst = {{0}};
  float src = -2147.483;
  s21_decimal result = {{2147482, 0, 0, 2147680256}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_10) {
  s21_decimal dst = {{0}};
  float src = -0.2147483;
  s21_decimal result = {{214748, 0, 0, 2147876864}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_11) {
  s21_decimal dst = {{0}};
  float src = -500.0;
  s21_decimal result = {{500, 0, 0, NEGATIVE_INT}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(float_to_decimal_12) {
  s21_decimal dst = {{0}};
  float src = 50.0;
  s21_decimal result = {{50, 0, 0, 0}};
  int return_code = s21_from_float_to_decimal(src, &dst);
  int return_value = s21_is_equal(result, dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_int_eq(return_value, 1);

  // S21_DECIMAL_TO_FLOAT
  //---------------------------------------
}
END_TEST

START_TEST(decimal_to_float_1) {
  s21_decimal src = {{5, 0, 0, 2147483648}};
  float dst = 0;
  float result = -5.0;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_2) {
  s21_decimal src = {{5, 0, 0, 0}};
  float dst = 0;
  float result = 5;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_3) {
  s21_decimal src = {{36, 0, 0, 65536}};
  float dst = 0;
  float result = 3.6;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_4) {
  s21_decimal src = {{0, 0, 0, 0}};
  float dst = 0;
  float result = 0;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_5) {
  s21_decimal src = {{4294967295, 0, 0, 131072}};
  float dst = 0;
  float result = 42949672.000000;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_6) {
  s21_decimal src = {{4294967295, 0, 0, 2147614720}};
  float dst = 0;
  float result = -42949672;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_7) {
  s21_decimal src = {{4294967295, 0, 0, 2147614720}};
  float dst = 0;
  float result = -42949672;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_8) {
  s21_decimal src = {{429496, 0, 0, 262144}};
  float dst = 0;
  float result = 42.9496;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_9) {
  s21_decimal src = {{429496, 0, 0, 2147745792}};
  float dst = 0;
  float result = -42.9496;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_10) {
  s21_decimal src = {{146432, 0, 0, NEGATIVE_INT}};
  float dst = 0;
  float result = -146432.0;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);
}
END_TEST

START_TEST(decimal_to_float_11) {
  s21_decimal src = {{146432, 0, 0, 393216}};
  float dst = 0;
  float result = 0.146432;
  int return_code = s21_from_decimal_to_float(src, &dst);
  ck_assert_int_eq(return_code, 0);
  ck_assert_float_eq(dst, result);

  /////////////////////////
  // COMPARISON
  /////////////////////////

  // S21_IS_NOT_EQUAL
  //---------------------------------------
}
END_TEST

START_TEST(not_equal_1) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_not_equal(x1, x2), 0);
}
END_TEST

START_TEST(not_equal_2) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  ck_assert_int_eq(s21_is_not_equal(x1, x2), 1);
}
END_TEST

START_TEST(not_equal_3) {
  s21_decimal x1 = {{369, 0, 0, NEGATIVE_INT}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  ck_assert_int_eq(s21_is_not_equal(x1, x2), 1);
}
END_TEST

START_TEST(not_equal_4) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  set_scale(2, &x2);
  ck_assert_int_eq(s21_is_not_equal(x1, x2), 1);
}
END_TEST

START_TEST(not_equal_5) {
  s21_decimal x1 = {{369, 0, 0, NEGATIVE_INT}};
  s21_decimal x2 = {{128, 0, 0, 0}};
  set_scale(2, &x1);
  ck_assert_int_eq(s21_is_not_equal(x1, x2), 1);
}
END_TEST

START_TEST(not_equal_6) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  set_scale(2, &x1);
  set_scale(2, &x2);
  ck_assert_int_eq(s21_is_not_equal(x1, x2), 0);

  // S21_IS_LESS_OR_EQUAL
  //---------------------------------------
}
END_TEST

START_TEST(less_or_equal_1) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less_or_equal(x1, x2), 1);
}
END_TEST

START_TEST(less_or_equal_2) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less_or_equal(x1, x2), 1);
}
END_TEST

START_TEST(less_or_equal_3) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less_or_equal(x1, x2), 0);
}
END_TEST

START_TEST(less_or_equal_4) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, NEGATIVE_INT}};
  ck_assert_int_eq(s21_is_less_or_equal(x1, x2), 0);
}
END_TEST

START_TEST(less_or_equal_5) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  set_scale(3, &x1);
  set_scale(2, &x2);
  ck_assert_int_eq(s21_is_less_or_equal(x1, x2), 1);
}
END_TEST

START_TEST(less_or_equal_6) {
  s21_decimal x1 = {{123456789, 0, 0, 0}};
  s21_decimal x2 = {{123456789, 0, 0, 0}};
  set_scale(2, &x1);
  set_scale(3, &x2);
  ck_assert_int_eq(s21_is_less_or_equal(x1, x2), 0);
}
END_TEST

START_TEST(less_or_equal_7) {
  s21_decimal x1 = {{123456788, 0, 0, 0}};
  s21_decimal x2 = {{123456789, 0, 0, 0}};
  set_scale(2, &x2);
  set_sign(&x1);
  ck_assert_int_eq(s21_is_less_or_equal(x1, x2), 1);

  // S21_IS_LESS
  //---------------------------------------
}
END_TEST

START_TEST(less_1) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less(x1, x2), 0);
}
END_TEST

START_TEST(less_2) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{128963, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less(x1, x2), 1);
}
END_TEST

START_TEST(less_3) {
  s21_decimal x1 = {{369, 0, 0, NEGATIVE_INT}};
  s21_decimal x2 = {{128963, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less(x1, x2), 1);
}
END_TEST

START_TEST(less_4) {
  s21_decimal x1 = {{128963, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, NEGATIVE_INT}};
  ck_assert_int_eq(s21_is_less(x1, x2), 0);
}
END_TEST

START_TEST(less_5) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{3, 0, 0, 0}};
  set_scale(3, &x1);
  ck_assert_int_eq(s21_is_less(x1, x2), 1);
}
END_TEST

START_TEST(less_6) {
  s21_decimal x1 = {{128, 0, 0, 0}};
  s21_decimal x2 = {{128, 0, 0, 0}};
  set_scale(3, &x1);
  set_scale(2, &x2);
  ck_assert_int_eq(s21_is_less(x1, x2), 1);
}
END_TEST

START_TEST(less_7) {
  s21_decimal x1 = {{128, 0, 0, 0}};
  s21_decimal x2 = {{128, 0, 0, 0}};
  set_scale(3, &x1);
  set_scale(2, &x2);
  set_sign(&x2);
  ck_assert_int_eq(s21_is_less(x1, x2), 0);

  // S21_IS_GREATER
  //---------------------------------------
}
END_TEST

START_TEST(greater_1) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater(x1, x2), 0);
}
END_TEST

START_TEST(greater_2) {
  s21_decimal x1 = {{369, 0, 0, NEGATIVE_INT}};
  s21_decimal x2 = {{128963, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater(x1, x2), 0);
}
END_TEST

START_TEST(greater_3) {
  s21_decimal x1 = {{128963, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, NEGATIVE_INT}};
  ck_assert_int_eq(s21_is_greater(x1, x2), 1);
}
END_TEST

START_TEST(greater_4) {
  s21_decimal x1 = {{128, 0, 0, 0}};
  s21_decimal x2 = {{128, 0, 0, 0}};
  set_scale(2, &x1);
  set_scale(3, &x2);
  ck_assert_int_eq(s21_is_greater(x1, x2), 1);
}
END_TEST

START_TEST(greater_5) {
  s21_decimal x1 = {{128, 0, 0, 0}};
  s21_decimal x2 = {{128, 0, 0, 0}};
  set_scale(2, &x1);
  set_scale(3, &x2);
  set_sign(&x1);
  ck_assert_int_eq(s21_is_greater(x1, x2), 0);

  // S21_IS_GREATER_OR_EQUAL
  //---------------------------------------
}
END_TEST

START_TEST(greater_or_equal_1) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater_or_equal(x1, x2), 1);
}
END_TEST

START_TEST(greater_or_equal_2) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater_or_equal(x1, x2), 0);
}
END_TEST

START_TEST(greater_or_equal_3) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater_or_equal(x1, x2), 1);
}
END_TEST

START_TEST(greater_or_equal_4) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, NEGATIVE_INT}};
  ck_assert_int_eq(s21_is_greater_or_equal(x1, x2), 1);
}
END_TEST

START_TEST(greater_or_equal_5) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  set_scale(3, &x1);
  set_scale(2, &x2);
  ck_assert_int_eq(s21_is_greater_or_equal(x1, x2), 0);
}
END_TEST

START_TEST(greater_or_equal_6) {
  s21_decimal x1 = {{123456789, 0, 0, 0}};
  s21_decimal x2 = {{123456789, 0, 0, 0}};
  set_scale(2, &x1);
  set_scale(3, &x2);
  ck_assert_int_eq(s21_is_greater_or_equal(x1, x2), 1);
}
END_TEST

START_TEST(greater_or_equal_7) {
  s21_decimal x1 = {{123456788, 0, 0, 0}};
  s21_decimal x2 = {{123456789, 0, 0, 0}};
  set_scale(2, &x2);
  set_sign(&x1);
  ck_assert_int_eq(s21_is_greater_or_equal(x1, x2), 0);

  // S21_IS_EQUAL
  //---------------------------------------
}
END_TEST

START_TEST(equal_1) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_equal(x1, x2), 1);
}
END_TEST

START_TEST(equal_2) {
  s21_decimal x1 = {{0, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  ck_assert_int_eq(s21_is_equal(x1, x2), 0);
}
END_TEST

START_TEST(equal_3) {
  s21_decimal x1 = {{369, 0, 0, NEGATIVE_INT}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  ck_assert_int_eq(s21_is_equal(x1, x2), 0);
}
END_TEST

START_TEST(equal_4) {
  s21_decimal x1 = {{369, 0, 0, 0}};
  s21_decimal x2 = {{369, 0, 0, 0}};
  set_scale(2, &x2);
  ck_assert_int_eq(s21_is_equal(x1, x2), 0);
}
END_TEST

START_TEST(equal_5) {
  s21_decimal x1 = {{-369, 0, 0, 0}};
  s21_decimal x2 = {{128, 0, 0, 0}};
  set_scale(2, &x1);
  ck_assert_int_eq(s21_is_equal(x1, x2), 0);
}
END_TEST

START_TEST(equal_6) {
  s21_decimal x1 = {{3600, 0, 0, 0}};
  s21_decimal x2 = {{360, 0, 0, 0}};
  set_scale(1, &x1);
  ck_assert_int_eq(s21_is_equal(x1, x2), 1);

  /////////////////////////
  // OTHER
  /////////////////////////

  // S21_TRUNCATE
  //---------------------------------------
}
END_TEST

START_TEST(truncate_1) {
  // 264107318112051817.4866968866
  s21_decimal value = {{4231458, 142607504, 143172864, 0}};
  set_scale(10, &value);
  // 264107318112051817
  s21_decimal result = {{3735446121, 61492276, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_2) {
  // 975909603428014204144180.7086
  s21_decimal value = {{152218350, 399689840, 529041656, 0}};
  set_scale(4, &value);
  // 975909603428014204144180
  s21_decimal result = {{865880628, 711286553, 52904, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_3) {
  // 35127093725958791885374.000000
  s21_decimal value = {{1385335680, 2316373509, 1904243566, 0}};
  set_scale(6, &value);
  // 35127093725958791885374
  s21_decimal result = {{3397513790, 1046110320, 1904, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_4) {
  // 11301643024.744584584724317966
  s21_decimal value = {{1073317646, 17980054, 612663296, 0}};
  set_scale(18, &value);
  // 11301643024
  s21_decimal result = {{2711708432, 2, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_5) {
  // 5947153396147561.664
  s21_decimal value = {{572662976, 1384679553, 0, 0}};
  set_scale(3, &value);
  // 5947153396147561
  s21_decimal result = {{2375689577, 1384679, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_6) {
  // -919639.1385315400060
  s21_decimal value = {{2301614460, 2141201725, 0, NEGATIVE_INT}};
  set_scale(13, &value);
  // -1919639
  s21_decimal result = {{919639, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_7) {
  // -9876.540164283795735
  s21_decimal value = {{2248378647, 2299561203, 0, NEGATIVE_INT}};
  set_scale(15, &value);
  // -9876
  s21_decimal result = {{9876, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_8) {
  // -3031287.3475492500523254791
  s21_decimal value = {{4161864711, 703603086, 1643264, NEGATIVE_INT}};
  set_scale(19, &value);
  // -3031287
  s21_decimal result = {{3031287, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_9) {
  // -7922816.2514264337593543950335
  s21_decimal value = {{4294967295, 4294967295, 4294967295, NEGATIVE_INT}};
  set_scale(22, &value);
  // -7922816
  s21_decimal result = {{7922816, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(truncate_10) {
  // 7777777.7777777
  s21_decimal value = {{215014513, 18109, 0, 0}};
  set_scale(7, &value);
  // 7777777
  s21_decimal result = {{7777777, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_truncate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);

  // S21_NEGATE
  //---------------------------------------
}
END_TEST

START_TEST(negate_1) {
  s21_decimal value = {{109646720, 1610664704, 143720576, 0}};
  s21_decimal result = {{109646720, 1610664704, 143720576, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_negate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(negate_2) {
  s21_decimal value = {{109646720, 2433979235, 291922910, 0}};
  s21_decimal result = {{109646720, 2433979235, 291922910, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_negate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(negate_3) {
  s21_decimal value = {{11899227, 625325842, 1229594224, NEGATIVE_INT}};
  s21_decimal result = {{11899227, 625325842, 1229594224, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_negate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(negate_4) {
  s21_decimal value = {{11899227, 625325842, 1229594224, NEGATIVE_INT}};
  set_scale(0, &value);
  s21_decimal result = {{11899227, 625325842, 1229594224, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_negate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(negate_5) {
  s21_decimal value = {{851484950, 1767553039, 1225342115, 0}};
  set_scale(18, &value);
  s21_decimal result = {{851484950, 1767553039, 1225342115, 2148663296}};
  s21_decimal my_result = {{0}};
  int return_error = s21_negate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(negate_6) {
  s21_decimal value = {{851484950, 1767553039, 1225342115, 1179648}};
  set_scale(18, &value);
  s21_decimal result = {{851484950, 1767553039, 1225342115, 2148663296}};
  s21_decimal my_result = {{0}};
  int return_error = s21_negate(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);

  // S21_FLOOR
  //---------------------------------------
}
END_TEST

START_TEST(floor_1) {
  // 14990680192016484.7304647104
  s21_decimal value = {{25764288, 67043777, 8126464, 0}};
  set_scale(10, &value);
  // 14990680192016484
  s21_decimal result = {{3083427940, 3490289, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_2) {
  // 39697459361519.128505637404963
  s21_decimal value = {{19923235, 411042304, 2152003584, 0}};
  set_scale(15, &value);
  // 39697459361519
  s21_decimal result = {{3371611887, 9242, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_3) {
  s21_decimal value = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_4) {
  // 7922816251426433759354395033.5
  s21_decimal value = {{4294967295, 4294967295, 4294967295, 0}};
  set_scale(1, &value);
  // 7922816251426433759354395033
  s21_decimal result = {{2576980377, 2576980377, 429496729, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_5) {
  // -330034358.000060563
  s21_decimal value = {{4491411, 76842112, 0, NEGATIVE_INT}};
  set_scale(9, &value);
  // -330034359
  s21_decimal result = {{330034359, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_6) {
  // -7922816251426433759354395033.5
  s21_decimal value = {{4294967295, 4294967295, 4294967295, NEGATIVE_INT}};
  set_scale(1, &value);
  // -7922816251426433759354395034
  s21_decimal result = {{2576980378, 2576980377, 429496729, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_7) {
  // -25332308.1000455680
  s21_decimal value = {{7376384, 58981376, 0, NEGATIVE_INT}};
  set_scale(10, &value);
  // -25332309
  s21_decimal result = {{25332309, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_8) {
  // 0.00000000003452810109649558
  s21_decimal value = {{1049238, 803920, 0, 0}};
  set_scale(26, &value);
  // 0
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_9) {
  // -0.000000000004959928320
  s21_decimal value = {{664961024, 1, 0, NEGATIVE_INT}};
  set_scale(21, &value);
  // -1
  s21_decimal result = {{1, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_10) {
  // 27149251.7085128960
  s21_decimal value = {{2148083968, 63211777, 0, 0}};
  set_scale(10, &value);
  // 27149251
  s21_decimal result = {{27149251, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_11) {
  // 9904296572294616.931377348608
  s21_decimal value = {{3758096384, 133693441, 536912993, 0}};
  set_scale(12, &value);
  // 9904296572294616
  s21_decimal result = {{3203470808, 2306023, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_12) {
  // 22337854.19752363009
  s21_decimal value = {{281629697, 520093697, 0, 0}};
  set_scale(11, &value);
  // 22337854
  s21_decimal result = {{22337854, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_13) {
  // -8196555174.425465492
  s21_decimal value = {{25498260, 1908409217, 0, NEGATIVE_INT}};
  set_scale(9, &value);
  // -8196555175
  s21_decimal result = {{3901587879, 1, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_14) {
  // -3.1957442962838464
  s21_decimal value = {{62575552, 7440672, 0, NEGATIVE_INT}};
  set_scale(16, &value);
  // -4
  s21_decimal result = {{4, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(floor_15) {
  // -3965175934092449816848.5532975
  s21_decimal value = {{62575552, 7440672, 0, NEGATIVE_INT}};
  set_scale(16, &value);
  // -3965175934092449816849
  s21_decimal result = {{4, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_floor(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);

  // S21_ROUND
  //---------------------------------------
}
END_TEST

START_TEST(round_1) {
  // 349738609805692.312931738872
  s21_decimal value = {{1236477176, 118839973, 18959368, 0}};
  set_scale(12, &value);
  // 349738609805692
  s21_decimal result = {{3717859708, 81429, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_2) {
  s21_decimal value = {{0, 0, 0, 0}};
  set_scale(16, &value);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_3) {
  // 330121751632009242242.714390
  s21_decimal value = {{2090863382, 65314542, 17895936, 0}};
  set_scale(6, &value);
  // 330121751632009242243
  s21_decimal result = {{2678335107, 3848015884, 17, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_4) {
  // 4247984203.5
  s21_decimal value = {{3825136371, 9, 0, 0}};
  set_scale(1, &value);
  // 4247984204
  s21_decimal result = {{4247984204, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_5) {
  // 7895075245720457.50000001
  s21_decimal value = {{3023264129, 1239814178, 42799, 0}};
  set_scale(8, &value);
  // 7895075245720458
  s21_decimal result = {{1937703818, 1838215, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_6) {
  // 89057937594.5000000001
  s21_decimal value = {{583637505, 1195739118, 48, 0}};
  set_scale(10, &value);
  // 89057937595
  s21_decimal result = {{3158591675, 20, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_7) {
  // 641978563.5000000000
  s21_decimal value = {{2220137984, 1494722821, 0, 0}};
  set_scale(10, &value);
  // 641978564
  s21_decimal result = {{641978564, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_8) {
  // 0.465
  s21_decimal value = {{465, 0, 0, 0}};
  set_scale(3, &value);
  // 0
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_9) {
  // -908745357.386764378
  s21_decimal value = {{2052247642, 211583766, 0, NEGATIVE_INT}};
  set_scale(9, &value);
  // -908745357
  s21_decimal result = {{908745357, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_10) {
  // -832381902.74234
  s21_decimal value = {{1724077754, 19380, 0, NEGATIVE_INT}};
  set_scale(5, &value);
  // -832381903
  s21_decimal result = {{832381903, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_11) {
  // -758932283451.50000001
  s21_decimal value = {{2454047617, 490400020, 4, NEGATIVE_INT}};
  set_scale(8, &value);
  // -758932283452
  s21_decimal result = {{3018039356, 176, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(round_12) {
  // -758932283451.50000001
  s21_decimal value = {{2454047617, 490400020, 4, NEGATIVE_INT}};
  // -758932283452
  s21_decimal result = {{2454047617, 490400020, 4, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_round(value, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);

  /////////////////////////
  // ARITHMETIC
  /////////////////////////

  // S21_ADD
  //---------------------------------------
}
END_TEST

START_TEST(add_1) {
  s21_decimal src1 = {{27, 0, 0, 0}};
  s21_decimal src2 = {{19, 0, 0, 0}};
  s21_decimal result = {{46, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_2) {
  s21_decimal src1 = {{27, 0, 0, 2147483648}};
  s21_decimal src2 = {{19, 0, 0, 0}};
  s21_decimal result = {{8, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_3) {
  s21_decimal src1 = {{27, 0, 0, 2147483648}};
  s21_decimal src2 = {{19, 0, 0, 2147483648}};
  s21_decimal result = {{46, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_4) {
  s21_decimal src1 = {{27, 0, 0, 0}};
  s21_decimal src2 = {{19, 0, 0, 2147483648}};
  s21_decimal result = {{8, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_5) {
  s21_decimal src1 = {{27, 0, 0, 0}};
  s21_decimal src2 = {{27, 0, 0, 0}};
  s21_decimal result = {{54, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_6) {
  s21_decimal src1 = {{19, 0, 0, 0}};
  s21_decimal src2 = {{19, 0, 0, 0}};
  s21_decimal result = {{38, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_7) {
  s21_decimal src1 = {{19, 0, 0, 0}};
  s21_decimal src2 = {{27, 0, 0, 2147483648}};
  s21_decimal result = {{8, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_8) {
  s21_decimal src1 = {{19, 0, 0, 2147483648}};
  s21_decimal src2 = {{27, 0, 0, 2147483648}};
  s21_decimal result = {{46, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_9) {
  s21_decimal src1 = {{19, 0, 0, 2147483648}};
  s21_decimal src2 = {{27, 0, 0, 0}};
  s21_decimal result = {{8, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_10) {
  s21_decimal src1 = {{0, 0, 0, 0}};
  s21_decimal src2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_11) {
  s21_decimal src1 = {{812, 0, 0, 0}};
  s21_decimal src2 = {{5, 0, 0, 0}};
  s21_decimal result = {{817, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_12) {
  s21_decimal src1 = {{7, 0, 0, 0}};
  s21_decimal src2 = {{1407843, 0, 0, 0}};
  s21_decimal result = {{1407850, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_13) {
  s21_decimal src1 = {{4294967295, 4294967295, 0, 0}};
  s21_decimal src2 = {{1, 0, 0, 0}};
  s21_decimal result = {{0, 0, 1, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(add_14) {
  s21_decimal src1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal src2 = {{1, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  ck_assert_int_eq(return_error, 1);
}
END_TEST

START_TEST(add_15) {
  s21_decimal src1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal src2 = {{1, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_add(src1, src2, &my_result);
  ck_assert_int_eq(return_error, 0);

  // S21_SUB
  //---------------------------------------
}
END_TEST

START_TEST(sub_1) {
  s21_decimal src1 = {{27, 0, 0, 0}};
  s21_decimal src2 = {{19, 0, 0, 0}};
  s21_decimal result = {{8, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_2) {
  s21_decimal src1 = {{27, 0, 0, 2147483648}};
  s21_decimal src2 = {{19, 0, 0, 0}};
  s21_decimal result = {{46, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_3) {
  s21_decimal src1 = {{27, 0, 0, 2147483648}};
  s21_decimal src2 = {{19, 0, 0, 2147483648}};
  s21_decimal result = {{8, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_4) {
  s21_decimal src1 = {{27, 0, 0, 0}};
  s21_decimal src2 = {{19, 0, 0, 2147483648}};
  s21_decimal result = {{46, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_5) {
  s21_decimal src1 = {{27, 0, 0, 0}};
  s21_decimal src2 = {{27, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_6) {
  s21_decimal src1 = {{19, 0, 0, 0}};
  s21_decimal src2 = {{27, 0, 0, 0}};
  s21_decimal result = {{8, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_7) {
  s21_decimal src1 = {{19, 0, 0, 0}};
  s21_decimal src2 = {{27, 0, 0, 2147483648}};
  s21_decimal result = {{46, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_8) {
  s21_decimal src1 = {{19, 0, 0, 2147483648}};
  s21_decimal src2 = {{27, 0, 0, 2147483648}};
  s21_decimal result = {{8, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_9) {
  s21_decimal src1 = {{19, 0, 0, 2147483648}};
  s21_decimal src2 = {{27, 0, 0, 0}};
  s21_decimal result = {{46, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_10) {
  s21_decimal src1 = {{0, 0, 0, 0}};
  s21_decimal src2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_11) {
  s21_decimal src1 = {{812, 0, 0, 0}};
  s21_decimal src2 = {{5, 0, 0, 0}};
  s21_decimal result = {{807, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_12) {
  s21_decimal src1 = {{7, 0, 0, 0}};
  s21_decimal src2 = {{1407843, 0, 0, 0}};
  s21_decimal result = {{1407836, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_13) {
  s21_decimal src1 = {{27, 0, 0, 655360}};
  s21_decimal src2 = {{19, 0, 0, 983040}};
  s21_decimal result = {{2699981, 0, 0, 983040}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(sub_14) {
  s21_decimal src1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal src2 = {{1, 0, 0, 2147483648}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  ck_assert_int_eq(return_error, 1);
}
END_TEST

START_TEST(sub_15) {
  s21_decimal src1 = {{4294967295, 4294967295, 4294967295, 2147483648}};
  s21_decimal src2 = {{1, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  ck_assert_int_eq(return_error, 2);
}
END_TEST

START_TEST(sub_16) {
  s21_decimal src1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal src2 = {{4, 0, 0, 2147549184}};
  s21_decimal result = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_sub(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);

  // S21_MUL
  //---------------------------------------
}
END_TEST

START_TEST(mul_1) {
  s21_decimal src1 = {{27, 0, 0, 0}};
  s21_decimal src2 = {{19, 0, 0, 0}};
  s21_decimal result = {{513, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_2) {
  s21_decimal src1 = {{691798043, 621365760, 0, 0}};
  s21_decimal src2 = {{275, 0, 0, 0}};
  s21_decimal result = {{1265900801, 3371859500, 39, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_3) {
  s21_decimal src1 = {{0, 0, 0, 0}};
  s21_decimal src2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_4) {
  s21_decimal src1 = {{0, 0, 0, 0}};
  s21_decimal src2 = {{795136, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_5) {
  s21_decimal src1 = {{76303104, 0, 37440, 0}};
  s21_decimal src2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_6) {
  s21_decimal src1 = {{0, 0, 0, 2147483648}};
  s21_decimal src2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_7) {
  s21_decimal src1 = {{340935306, 29962228, 706814977, 0}};
  s21_decimal src2 = {{0, 152043520, 268435456, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 1);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_8) {
  s21_decimal src1 = {{308809984, 38021888, 67108864, 0}};
  s21_decimal src2 = {{138971468, 68296827, 285212688, 2147483648}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 2);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_9) {
  s21_decimal src1 = {{583354408, 72089672, 287581736, 2148466688}};
  s21_decimal src2 = {{356821490, 71844948, 1160, 1245184}};
  s21_decimal result = {{2399045302, 1585936326, 615382689, 2148270080}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_10) {
  s21_decimal src1 = {{3797176584, 1631814980, 17847570, 720896}};
  s21_decimal src2 = {{1470649620, 1395151940, 340874378, 2148597760}};
  s21_decimal result = {{3972489836, 2586074978, 1122259226, 2147614720}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_11) {
  s21_decimal src1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal src2 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 1);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_12) {
  s21_decimal src1 = {{4294967295, 4294967295, 4294967295, 1179648}};
  s21_decimal src2 = {{4294967295, 4294967295, 4294967295, 2148466688}};
  s21_decimal result = {{158262358, 899300158, 3402823669, 2147745792}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_13) {
  s21_decimal src1 = {{0, 0, 0, 0}};
  s21_decimal src2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(mul_14) {
  s21_decimal src1 = {{0, 0, 0, 0}};
  s21_decimal src2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_mul(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);

  // S21_DIV
  //---------------------------------------
}
END_TEST

START_TEST(div_1) {
  s21_decimal src1 = {{10000, 0, 0, 0}};
  set_scale(2, &src1);
  s21_decimal src2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_div(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 3);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(div_2) {
  s21_decimal src1 = {{10000, 0, 0, 0}};
  set_scale(2, &src1);
  s21_decimal src2 = {{5, 0, 0, 0}};
  s21_decimal result = {{20, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_div(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(div_3) {
  s21_decimal src1 = {{10000, 0, 0, 0}};
  set_scale(2, &src1);
  s21_decimal src2 = {{50, 0, 0, 0}};
  s21_decimal result = {{2, 0, 0, 0}};
  s21_decimal my_result = {{0}};
  int return_error = s21_div(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(div_4) {
  s21_decimal src1 = {{10000, 0, 0, 0}};
  set_scale(2, &src1);
  s21_decimal src2 = {{50, 0, 0, NEGATIVE_INT}};
  s21_decimal result = {{2, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_div(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(div_5) {
  s21_decimal src1 = {{100000, 0, 0, 0}};
  set_scale(2, &src1);
  s21_decimal src2 = {{50, 0, 0, NEGATIVE_INT}};
  s21_decimal result = {{20, 0, 0, NEGATIVE_INT}};
  s21_decimal my_result = {{0}};
  int return_error = s21_div(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(div_6) {
  s21_decimal src1 = {{1234567, 0, 0, 0}};
  set_scale(5, &src1);
  s21_decimal src2 = {{2, 0, 0, 0}};
  s21_decimal result = {{6172835, 0, 0, 393216}};
  s21_decimal my_result = {{0}};
  int return_error = s21_div(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

START_TEST(div_7) {
  s21_decimal src1 = {{25, 0, 0, NEGATIVE_INT}};
  set_scale(1, &src1);
  s21_decimal src2 = {{2, 0, 0, 0}};
  s21_decimal result = {{125, 0, 0, 2147614720}};
  s21_decimal my_result = {{0}};
  int return_error = s21_div(src1, src2, &my_result);
  int return_value = s21_is_equal(result, my_result);
  ck_assert_int_eq(return_error, 0);
  ck_assert_int_eq(return_value, 1);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("\x1b[93;105ms21_decimal\x1b[0;0m");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, int_to_decimal_1);
  tcase_add_test(tc1_1, int_to_decimal_2);
  tcase_add_test(tc1_1, int_to_decimal_3);
  tcase_add_test(tc1_1, int_to_decimal_4);
  tcase_add_test(tc1_1, int_to_decimal_5);
  tcase_add_test(tc1_1, int_to_decimal_6);
  tcase_add_test(tc1_1, int_to_decimal_7);
  tcase_add_test(tc1_1, decimal_to_int_1);
  tcase_add_test(tc1_1, decimal_to_int_2);
  tcase_add_test(tc1_1, decimal_to_int_3);
  tcase_add_test(tc1_1, decimal_to_int_4);
  tcase_add_test(tc1_1, decimal_to_int_5);
  tcase_add_test(tc1_1, decimal_to_int_6);
  tcase_add_test(tc1_1, decimal_to_int_7);
  tcase_add_test(tc1_1, decimal_to_int_8);
  tcase_add_test(tc1_1, decimal_to_int_9);
  tcase_add_test(tc1_1, decimal_to_int_10);
  tcase_add_test(tc1_1, decimal_to_int_11);
  tcase_add_test(tc1_1, decimal_to_int_12);
  tcase_add_test(tc1_1, decimal_to_int_13);
  tcase_add_test(tc1_1, decimal_to_int_14);
  tcase_add_test(tc1_1, float_to_decimal_1);
  tcase_add_test(tc1_1, float_to_decimal_2);
  tcase_add_test(tc1_1, float_to_decimal_3);
  tcase_add_test(tc1_1, float_to_decimal_4);
  tcase_add_test(tc1_1, float_to_decimal_5);
  tcase_add_test(tc1_1, float_to_decimal_6);
  tcase_add_test(tc1_1, float_to_decimal_7);
  tcase_add_test(tc1_1, float_to_decimal_8);
  tcase_add_test(tc1_1, float_to_decimal_9);
  tcase_add_test(tc1_1, float_to_decimal_10);
  tcase_add_test(tc1_1, float_to_decimal_11);
  tcase_add_test(tc1_1, float_to_decimal_12);
  tcase_add_test(tc1_1, decimal_to_float_1);
  tcase_add_test(tc1_1, decimal_to_float_2);
  tcase_add_test(tc1_1, decimal_to_float_3);
  tcase_add_test(tc1_1, decimal_to_float_4);
  tcase_add_test(tc1_1, decimal_to_float_5);
  tcase_add_test(tc1_1, decimal_to_float_6);
  tcase_add_test(tc1_1, decimal_to_float_7);
  tcase_add_test(tc1_1, decimal_to_float_8);
  tcase_add_test(tc1_1, decimal_to_float_9);
  tcase_add_test(tc1_1, decimal_to_float_10);
  tcase_add_test(tc1_1, decimal_to_float_11);
  tcase_add_test(tc1_1, not_equal_1);
  tcase_add_test(tc1_1, not_equal_2);
  tcase_add_test(tc1_1, not_equal_3);
  tcase_add_test(tc1_1, not_equal_4);
  tcase_add_test(tc1_1, not_equal_5);
  tcase_add_test(tc1_1, not_equal_6);
  tcase_add_test(tc1_1, less_or_equal_1);
  tcase_add_test(tc1_1, less_or_equal_2);
  tcase_add_test(tc1_1, less_or_equal_3);
  tcase_add_test(tc1_1, less_or_equal_4);
  tcase_add_test(tc1_1, less_or_equal_5);
  tcase_add_test(tc1_1, less_or_equal_6);
  tcase_add_test(tc1_1, less_or_equal_7);
  tcase_add_test(tc1_1, less_1);
  tcase_add_test(tc1_1, less_2);
  tcase_add_test(tc1_1, less_3);
  tcase_add_test(tc1_1, less_4);
  tcase_add_test(tc1_1, less_5);
  tcase_add_test(tc1_1, less_6);
  tcase_add_test(tc1_1, less_7);
  tcase_add_test(tc1_1, greater_1);
  tcase_add_test(tc1_1, greater_2);
  tcase_add_test(tc1_1, greater_3);
  tcase_add_test(tc1_1, greater_4);
  tcase_add_test(tc1_1, greater_5);
  tcase_add_test(tc1_1, greater_or_equal_1);
  tcase_add_test(tc1_1, greater_or_equal_2);
  tcase_add_test(tc1_1, greater_or_equal_3);
  tcase_add_test(tc1_1, greater_or_equal_4);
  tcase_add_test(tc1_1, greater_or_equal_5);
  tcase_add_test(tc1_1, greater_or_equal_6);
  tcase_add_test(tc1_1, greater_or_equal_7);
  tcase_add_test(tc1_1, equal_1);
  tcase_add_test(tc1_1, equal_2);
  tcase_add_test(tc1_1, equal_3);
  tcase_add_test(tc1_1, equal_4);
  tcase_add_test(tc1_1, equal_5);
  tcase_add_test(tc1_1, equal_6);
  tcase_add_test(tc1_1, truncate_1);
  tcase_add_test(tc1_1, truncate_2);
  tcase_add_test(tc1_1, truncate_3);
  tcase_add_test(tc1_1, truncate_4);
  tcase_add_test(tc1_1, truncate_5);
  tcase_add_test(tc1_1, truncate_6);
  tcase_add_test(tc1_1, truncate_7);
  tcase_add_test(tc1_1, truncate_8);
  tcase_add_test(tc1_1, truncate_9);
  tcase_add_test(tc1_1, truncate_10);
  tcase_add_test(tc1_1, negate_1);
  tcase_add_test(tc1_1, negate_2);
  tcase_add_test(tc1_1, negate_3);
  tcase_add_test(tc1_1, negate_4);
  tcase_add_test(tc1_1, negate_5);
  tcase_add_test(tc1_1, negate_6);
  tcase_add_test(tc1_1, floor_1);
  tcase_add_test(tc1_1, floor_2);
  tcase_add_test(tc1_1, floor_3);
  tcase_add_test(tc1_1, floor_4);
  tcase_add_test(tc1_1, floor_5);
  tcase_add_test(tc1_1, floor_6);
  tcase_add_test(tc1_1, floor_7);
  tcase_add_test(tc1_1, floor_8);
  tcase_add_test(tc1_1, floor_9);
  tcase_add_test(tc1_1, floor_10);
  tcase_add_test(tc1_1, floor_11);
  tcase_add_test(tc1_1, floor_12);
  tcase_add_test(tc1_1, floor_13);
  tcase_add_test(tc1_1, floor_14);
  tcase_add_test(tc1_1, floor_15);
  tcase_add_test(tc1_1, round_1);
  tcase_add_test(tc1_1, round_2);
  tcase_add_test(tc1_1, round_3);
  tcase_add_test(tc1_1, round_4);
  tcase_add_test(tc1_1, round_5);
  tcase_add_test(tc1_1, round_6);
  tcase_add_test(tc1_1, round_7);
  tcase_add_test(tc1_1, round_8);
  tcase_add_test(tc1_1, round_9);
  tcase_add_test(tc1_1, round_10);
  tcase_add_test(tc1_1, round_11);
  tcase_add_test(tc1_1, round_12);
  tcase_add_test(tc1_1, add_1);
  tcase_add_test(tc1_1, add_2);
  tcase_add_test(tc1_1, add_3);
  tcase_add_test(tc1_1, add_4);
  tcase_add_test(tc1_1, add_5);
  tcase_add_test(tc1_1, add_6);
  tcase_add_test(tc1_1, add_7);
  tcase_add_test(tc1_1, add_8);
  tcase_add_test(tc1_1, add_9);
  tcase_add_test(tc1_1, add_10);
  tcase_add_test(tc1_1, add_11);
  tcase_add_test(tc1_1, add_12);
  tcase_add_test(tc1_1, add_13);
  tcase_add_test(tc1_1, add_14);
  tcase_add_test(tc1_1, add_15);
  tcase_add_test(tc1_1, sub_1);
  tcase_add_test(tc1_1, sub_2);
  tcase_add_test(tc1_1, sub_3);
  tcase_add_test(tc1_1, sub_4);
  tcase_add_test(tc1_1, sub_5);
  tcase_add_test(tc1_1, sub_6);
  tcase_add_test(tc1_1, sub_7);
  tcase_add_test(tc1_1, sub_8);
  tcase_add_test(tc1_1, sub_9);
  tcase_add_test(tc1_1, sub_10);
  tcase_add_test(tc1_1, sub_11);
  tcase_add_test(tc1_1, sub_12);
  tcase_add_test(tc1_1, sub_13);
  tcase_add_test(tc1_1, sub_14);
  tcase_add_test(tc1_1, sub_15);
  tcase_add_test(tc1_1, sub_16);
  tcase_add_test(tc1_1, mul_1);
  tcase_add_test(tc1_1, mul_2);
  tcase_add_test(tc1_1, mul_3);
  tcase_add_test(tc1_1, mul_4);
  tcase_add_test(tc1_1, mul_5);
  tcase_add_test(tc1_1, mul_6);
  tcase_add_test(tc1_1, mul_7);
  tcase_add_test(tc1_1, mul_8);
  tcase_add_test(tc1_1, mul_9);
  tcase_add_test(tc1_1, mul_10);
  tcase_add_test(tc1_1, mul_11);
  tcase_add_test(tc1_1, mul_12);
  tcase_add_test(tc1_1, mul_13);
  tcase_add_test(tc1_1, mul_14);
  tcase_add_test(tc1_1, div_1);
  tcase_add_test(tc1_1, div_2);
  tcase_add_test(tc1_1, div_3);
  tcase_add_test(tc1_1, div_4);
  tcase_add_test(tc1_1, div_5);
  tcase_add_test(tc1_1, div_6);
  tcase_add_test(tc1_1, div_7);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
